// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calculate_distances
NumericMatrix calculate_distances(CharacterMatrix genetics, double NA_weight, int min_common_loci);
RcppExport SEXP _GenopowdimR_calculate_distances(SEXP geneticsSEXP, SEXP NA_weightSEXP, SEXP min_common_lociSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterMatrix >::type genetics(geneticsSEXP);
    Rcpp::traits::input_parameter< double >::type NA_weight(NA_weightSEXP);
    Rcpp::traits::input_parameter< int >::type min_common_loci(min_common_lociSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_distances(genetics, NA_weight, min_common_loci));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GenopowdimR_calculate_distances", (DL_FUNC) &_GenopowdimR_calculate_distances, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_GenopowdimR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
