# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculate_distances <- function(genetics, NA_weight, min_common_loci) {
    .Call(`_GenopowdimR_calculate_distances`, genetics, NA_weight, min_common_loci)
}

